language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true